"""Minimal local mock of an OpenAI-compatible Chat Completions endpoint.

Purpose: verify SPAgo's LLM call path (config, HTTP, validation, caching,
error states) in a browser without touching a real paid provider. It returns
a deterministic family summary whose citations echo fact_refs from the
request's user prompt.

Run:  python scripts/mock_llm_endpoint.py [--port 8101]
Then configure:
    SPAGO_LLM_BASE_URL=http://127.0.0.1:8101/v1
    SPAGO_LLM_API_KEY=            (empty → no Authorization header)
    SPAGO_LLM_MODEL=mock-model
Fault injection for error-state checks (set the model name accordingly):
    mock-error → HTTP 500; mock-timeout → stalls past the deadline;
    mock-rate-limit → HTTP 429 with Retry-After: 7;
    mock-rate-limit-bad-header → HTTP 429 with an unusable Retry-After;
    mock-reject-once → the first request answers with a rejected citation
    (unknown fact_ref), later requests answer normally, so the service's one
    bounded content re-sample can be observed end to end.
This is test tooling, clearly not a real model: do not present its output as
scientific evidence.
"""
from __future__ import annotations

import argparse
import json
import re
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

FACT_REF_RE = re.compile(r"(?:family|measurement|evidence):[A-Za-z0-9-]+")


def build_summary_content(user_prompt: str) -> str:
    refs = []
    seen = set()
    for ref in FACT_REF_RE.findall(user_prompt):
        if ref not in seen and ref.startswith("measurement:"):
            seen.add(ref)
            refs.append(ref)
    cited = refs[:3] or ["family:unknown"]

    paragraphs = [
        {
            "text": (
                "Mock summary: the family's stored records were received and echoed back "
                "by the local mock endpoint. This text demonstrates the call path, not "
                "scientific analysis."
            ),
            "fact_refs": [cited[0]],
        }
    ]
    if len(cited) > 1:
        paragraphs.append(
            {
                "text": f"The mock model cites {len(cited)} measurement records from the bounded input.",
                "fact_refs": cited,
            }
        )
    payload = {
        "paragraphs": paragraphs,
        "limitations": [
            "Generated by scripts/mock_llm_endpoint.py for call-path verification only."
        ],
    }
    return json.dumps(payload)


class Handler(BaseHTTPRequestHandler):
    #: Fault-injection budgets for the rejection modes: the first N requests per
    #: model are refused by SPAgo's validation, later requests answer normally.
    #: Two modes exist so both halves of the bounded re-sample can be exercised:
    #: the automatic second attempt succeeding (`mock-reject-once`) and both
    #: attempts being refused, which must settle as one failed row that still
    #: accounts both billed calls (`mock-reject-twice` — the runbook §H8 drill).
    rejections_left = {"mock-reject-once": 1, "mock-reject-twice": 2}

    def _send_json(self, status: int, payload: dict) -> None:
        encoded = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def do_POST(self):  # noqa: N802
        if not self.path.endswith("/chat/completions"):
            self.send_response(404)
            self.end_headers()
            return
        length = int(self.headers.get("Content-Length", 0))
        body = json.loads(self.rfile.read(length) or b"{}")
        user_prompt = next(
            (m.get("content", "") for m in body.get("messages", []) if m.get("role") == "user"),
            "",
        )
        # Optional fault injection for error-state verification:
        # model name "mock-error" → 500; "mock-timeout" → sleeps past deadlines;
        # "mock-rate-limit" → 429 with a Retry-After header (LLM-07);
        # "mock-rate-limit-bad-header" → 429 with an unusable Retry-After;
        # "mock-reject-once" → the first request is refused by SPAgo's citation
        # validation, later requests answer normally (one re-sample is allowed);
        # "mock-reject-twice" → the first two requests are refused, so the
        # bounded re-sample is exhausted and the request fails as 502 while both
        # billed attempts are accounted (runbook §H8).
        model = body.get("model", "mock-model")
        budget = Handler.rejections_left.get(model)
        if budget:
            Handler.rejections_left[model] = budget - 1
            rejected = {
                "paragraphs": [
                    {"text": "Rejected on purpose.", "fact_refs": ["family:not-a-real-ref"]}
                ],
                "limitations": [],
            }
            self._send_json(
                200,
                {
                    "id": "mock-rejection",
                    "model": model,
                    "choices": [
                        {
                            "index": 0,
                            "message": {"role": "assistant", "content": json.dumps(rejected)},
                            "finish_reason": "stop",
                        }
                    ],
                    "usage": {"prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2},
                },
            )
            return
        if model == "mock-error":
            self.send_response(500)
            self.end_headers()
            self.wfile.write(b'{"error": {"message": "mock internal error"}}')
            return
        if model == "mock-rate-limit":
            self.send_response(429)
            self.send_header("Retry-After", "7")
            self.end_headers()
            self.wfile.write(b'{"error": {"message": "mock rate limit"}}')
            return
        if model == "mock-rate-limit-bad-header":
            self.send_response(429)
            self.send_header("Retry-After", "later")
            self.end_headers()
            self.wfile.write(b'{"error": {"message": "mock rate limit"}}')
            return
        if model == "mock-timeout":
            time.sleep(90)
        content = build_summary_content(user_prompt)
        n_prompt = len(user_prompt) // 4
        response = {
            "id": "mock-completion",
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": content},
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": n_prompt,
                "completion_tokens": len(content) // 4,
                "total_tokens": n_prompt + len(content) // 4,
            },
        }
        self._send_json(200, response)
    def log_message(self, fmt, *args):  # keep test output readable
        print("[mock-llm]", fmt % args)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8101)
    parser.add_argument("--host", default="127.0.0.1", help="bind 0.0.0.0 so containers can reach it")
    args = parser.parse_args()
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"mock LLM endpoint on http://{args.host}:{args.port}/v1/chat/completions")
    server.serve_forever()


if __name__ == "__main__":
    main()
